DROP TABLE IF EXISTS SHIP;
CREATE TABLE SHIP (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    FILM VARCHAR(255) NOT NULL,
    CREATION_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP
);